services:
  - type: web
    name: gta2
    runtime: static
    repo: https://github.com/mrauter1/gta2
    branch: main
    buildCommand: "mkdir -p public && cp -R index.html src styles public/"
    staticPublishPath: public
    autoDeployTrigger: commit
